{
  "sudo": "required",
  "dist": "trusty",
  "language": "c",
  "before_script": [
    "sudo apt-get -qq update",
  ],
  "script": [
    "make ubuntudeps",
    "make",
    "make test_allemu",
  ],
  "env": "BITBOX=$TRAVIS_BUILD_DIR/bitbox",
  "group": "stable",
  "os": "linux"
}

